name: first

on: [push]

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@4
      - name: Step Two
        run: env | sort
  job2:
    name: Job2
    runs-on: windows-latest
    steps:
      - name: Step One
        uses: actions/checkout@4
      - name: Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"


